# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Ankur Agrawal
tagline:          'Senior Software Engineer, Medtronic'
description:      'Senior Software Engineer, Medtronic'
url:              http://ankur-agrawal.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
